### ISSUE TITLE
JD_dreamFactory.py，请问你是用什么抓包的呢

### ISSUE THREAD

**Issue by lxk0301** [Zero-S1/JD_tools#11]
JD_dreamFactory.py，京喜工厂这个，请问你是用什么抓包的呢？我pc上面用fiddler抓包app上面，里面拿不到数据，都是空的，京喜水果也是一样，抓包拿不到东西

**Comment by Zero-S1** [comment]
dreamFactory 用的 iOS surge
不过据我观察，限时的项目不拉人头完成不了，助力需要用到微信小程序  抓https://jxa.jd.com/wq.jd.com/dreamfactory/friend/AssistFriend 这个需要另外的登录

**Comment by lxk0301** [comment]
> dreamFactory 用的 iOS surge
> 不过据我观察，限时的项目不拉人头完成不了，助力需要用到微信小程序 抓https://jxa.jd.com/wq.jd.com/dreamfactory/friend/AssistFriend 这个需要另外的登录

我看了一下， 京喜工厂和京喜水果都是限时的，那看来有点坑。需要拉人头

**Comment by changer2222** [comment]
京喜就是以多人玩法为主的，所以这个累
To lxk0301:PC上面也可以Charles，将手机代理指过去就可以了
