### ISSUE TITLE
jingqiWorld.py 这个没法使用

### ISSUE THREAD

**Issue by changer2222** [Zero-S1/JD_tools#12]
{'code': '600', 'echo': 'signature verification failed'}

st /sign是动态的
openudid是哪来的？我抓包里面没有看到这个值。我只有uudi

**Comment by Zero-S1** [comment]
那试试将data里的全填进去吧
openudid可能iOS才有

**Comment by changer2222** [comment]
> 那试试将data里的全填进去吧
> openudid可能iOS才有

这个st是timestamp，sign和sv是变动的，你填进后能一直执行？还是？

**Comment by Zero-S1** [comment]
> > 那试试将data里的全填进去吧
> > openudid可能iOS才有
> 
> 这个st是timestamp，sign和sv是变动的，你填进后能一直执行？还是？
 
可行，不检查st的实时性，只要确定st body sv 等参数，sign也是固定的；
所以没法伪造全民红包里的data，因为data["body"]是变量；
安卓没有openudid的话，直接将data全填入就行
