### ISSUE TITLE
这个怎么用

### ISSUE THREAD

**Issue by yh3057** [Zero-S1/JD_tools#13]
需要通过什么软件来操作啊

**Comment by Zero-S1** [comment]
> 需要通过什么软件来操作啊

知道github，却不知道编程语言吗？😂
建议了解一下python3，上手难度很低的

**Comment by yh3057** [comment]
> > 需要通过什么软件来操作啊
> 
> 
> 
> 知道github，却不知道编程语言吗？😂
> 
> 建议了解一下python3，上手难度很低的

通过公众号链接跳转过来的

**Comment by Zero-S1** [comment]
> > > 需要通过什么软件来操作啊
> > 
> > 
> > 知道github，却不知道编程语言吗？😂
> > 建议了解一下python3，上手难度很低的
> 
> 通过公众号链接跳转过来的

哪个公众号？
