### ISSUE TITLE
京东水果浇水的时候,如果可以去兑换了, 状态码已经不是code=== '6'了

### ISSUE THREAD

**Issue by lxk0301** [Zero-S1/JD_tools#15]
京东水果浇水的时候,如果可以去兑换了, 状态码是code=== '0'了, finished = true(未成熟是false);
月初还是 code === '6',京东又换了
![image](https://user-images.githubusercontent.com/21308593/88885730-a3d1f100-d26b-11ea-8abf-18cb3400f30e.png)

**Comment by Zero-S1** [comment]
OK，感谢

**Comment by lxk0301** [comment]
> OK，感谢

我之前是拿code==='6'和finished判断, 导致一直不对

**Comment by lxk0301** [comment]
@Zero-S1  浇水阶段性奖励  ,指的是刚开始种植的时候, 有时候浇水,跳出来的水滴奖励吧?

**Comment by Zero-S1** [comment]
> @Zero-S1 浇水阶段性奖励 ,指的是刚开始种植的时候, 有时候浇水,跳出来的水滴奖励吧?

对，据我观察，应该也对应了 “initForFarm”返回的几个参数
```
{
'toBeginEnergy':30,  # 种植奖励
'toFlowEnergy':40,  # 开花奖励
'toFruitEnergy':50,   # 结果奖励
 
'toFlowTimes':20, #开花需要浇水次数
'toFruitTimes':59,
}
```
```
if waterInfo["waterStatus"] == 1:  # 开花
            print(postTemplate(cookies, "gotStageAwardForFarm", {"type": 1}))
if waterInfo["waterStatus"] == 2:  # 结果
            print(postTemplate(cookies, "gotStageAwardForFarm", {"type": 3}))
```
这里type=3比较奇怪
你可以抓包试一下，这个抓包周期比较长，不方便测试

**Comment by lxk0301** [comment]
@Zero-S1  type=3 ,其实应该是没有的. 因为 waterStatus = 3  是水果成熟可兑换了. 
我看你上面写的 waterStatus = 1 .为开花,  type=1;
waterStatus= 2 ,为结果.    type=2;
而waterStatus = 3, 我上面截图就有. 就是 水果成熟可兑换

**Comment by Zero-S1** [comment]
@lxk0301 奖励为50水的貌似才是最开始领取的，这个一般新种植的时候也顺便手动领了

**Comment by lxk0301** [comment]
> @lxk0301 奖励为50水的貌似才是最开始领取的，这个一般新种植的时候也顺便手动领了

对的, 不过我明天就可以兑换了, 我明天抓包测试一下吧.

**Comment by lxk0301** [comment]
@Zero-S1  `果树长成小果子了('toFruitEnergy':50,   # 结果奖励) 我弄出来了.`  下面给你抓包详情
![image](https://user-images.githubusercontent.com/21308593/88989849-23fd6280-d30f-11ea-9e54-2999a2076393.png)

### 这里是'果树长成小果子了'之前的最后一次浇水返回结果

waterStatus === '2' && treeEnergy === 590

### 这个是领取50g水滴的
```
const url = `https://api.m.jd.com/client.action?functionId=gotStageAwardForFarm`;
const method = `POST`;
const headers = {
'Cookie' :`这里是京东cookie`,
'Accept' : `*/*`,
'Connection' : `keep-alive`,
'Content-Type' : `application/x-www-form-urlencoded`,
'Accept-Encoding' : `gzip, deflate, br`,
'Host' : `api.m.jd.com`,
'User-Agent' : `JD4iPhone/167237 (iPhone; iOS 13.5.1; Scale/2.00)`,
'Accept-Language' : `zh-Hans-CN;q=1`
};
const body = `body有一大堆, 格式化后里面主要是body=%7B%22type%22%3A3%7D(即body={type: 3})`;
```

**Comment by Zero-S1** [comment]
@lxk0301 我以前也抓到了type=3，但是不清楚对应关系，刚才找了一下抓包记录


waterStatus | treeEnergy | reward water | type |  
-- | -- | -- | -- | --
0 | 10 | 30 | 1 | 种植
1 | 200 | 40 | 2 | 开花
2 | 590 | 50 | 3 | 结果

用treeEnergy判断就行了

**Comment by lxk0301** [comment]
> @lxk0301 我以前也抓到了type=3，但是不清楚对应关系，刚才找了一下抓包记录
> 
> waterStatus	treeEnergy	reward water	type	 
> 0	10	30	1	种植
> 1	200	40	2	开花
> 2	590	50	3	结果
> 用treeEnergy判断就行了

好的,  不过很好奇 ,这种phython文件, 如何跑定时任务(cron)呢?

**Comment by Zero-S1** [comment]
对，我是放在云服务器上跑，其实只要有台不关机的电脑就行；
本来打算用Qx跑的，只不过那会儿boxjs还没出现，做不了多账号

**Comment by lxk0301** [comment]
> 对，我是放在云服务器上跑，其实只要有台不关机的电脑就行；
> 本来打算用Qx跑的，只不过那会儿boxjs还没出现，做不了多账号

咦 , 你居然也知道圈x和boxjs , 现在boxjs可以多账号了.我手机上面圈x+boxjs跑了4个京东账号

**Comment by Zero-S1** [comment]
> > 对，我是放在云服务器上跑，其实只要有台不关机的电脑就行；
> > 本来打算用Qx跑的，只不过那会儿boxjs还没出现，做不了多账号
> 
> 咦 , 你居然也知道圈x和boxjs , 现在boxjs可以多账号了.我手机上面圈x+boxjs跑了4个京东账号

对我来说，还是习惯用电脑写，自用的有bug了也方便直接修改，python语法足够简单

**Comment by lxk0301** [comment]
> > > 对，我是放在云服务器上跑，其实只要有台不关机的电脑就行；
> > > 本来打算用Qx跑的，只不过那会儿boxjs还没出现，做不了多账号
> > 
> > 
> > 咦 , 你居然也知道圈x和boxjs , 现在boxjs可以多账号了.我手机上面圈x+boxjs跑了4个京东账号
> 
> 对我来说，还是习惯用电脑写，自用的有bug了也方便直接修改，python语法足够简单

大佬你宠汪汪和摇钱树，有兑换过东西吗？ 每次进去都显示抢光了。

**Comment by Zero-S1** [comment]
宠汪汪换过，摇钱树没有

**Comment by Zero-S1** [comment]
宠汪汪已推送

**Comment by lxk0301** [comment]
> 宠汪汪已推送

这个我可以参考你的，然后改下成我用的js吗？ 我这边领不到， 没办法抓包

**Comment by Zero-S1** [comment]
> > 宠汪汪已推送
> 
> 这个我可以参考你的，然后改下成我用的js吗？ 我这边领不到， 没办法抓包

你随意

**Comment by lxk0301** [comment]
> > > 宠汪汪已推送
> > 
> > 
> > 这个我可以参考你的，然后改下成我用的js吗？ 我这边领不到， 没办法抓包
> 
> 你随意

多谢。 不过我昨晚23点多去看一下， 居然能兑换20京豆。 然后去兑换。我自己也抓包到了

**Comment by lxk0301** [comment]
你好， 请问云函数， 你库里面的代码可以放到腾讯云函数上面吗？

**Comment by Zero-S1** [comment]
可以，刚才用阿里云试了一下
![Snipaste_2020-08-11_22-51-32](https://user-images.githubusercontent.com/23739314/89912592-4ce1f980-dc25-11ea-8c97-9667ecb193b5.png)
只不过每个定时脚本都需要jdCookie，有些麻烦

**Comment by lxk0301** [comment]
> 可以，刚才用阿里云试了一下
> ![Snipaste_2020-08-11_22-51-32](https://user-images.githubusercontent.com/23739314/89912592-4ce1f980-dc25-11ea-8c97-9667ecb193b5.png)
> 只不过每个定时脚本都需要jdCookie，有些麻烦

我用腾讯云, 运行你的脚本, 好像不行 .不知道是不是我不会玩这个
![image](https://user-images.githubusercontent.com/21308593/89968871-982cf400-dc87-11ea-91d5-eb34c477430d.png)
![image](https://user-images.githubusercontent.com/21308593/89968888-a3801f80-dc87-11ea-9cb2-6891eb59644b.png)

**Comment by mxzsw123456** [comment]
> 可以，刚才用阿里云试了一下
> ![Snipaste_2020-08-11_22-51-32](https://user-images.githubusercontent.com/23739314/89912592-4ce1f980-dc25-11ea-8c97-9667ecb193b5.png)
> 只不过每个定时脚本都需要jdCookie，有些麻烦
大佬你写的这些脚本上传到阿里云是不是还需要修改啊，我看着和我的下载下来的不太一样

**Comment by Zero-S1** [comment]
你用云函数运行的，还是直接服务器里跑的

**Comment by lxk0301** [comment]
> 你用云函数运行的，还是直接服务器里跑的

我吗?  我是直接在腾讯云函数运行的

**Comment by lxk0301** [comment]
> > 可以，刚才用阿里云试了一下
> > ![Snipaste_2020-08-11_22-51-32](https://user-images.githubusercontent.com/23739314/89912592-4ce1f980-dc25-11ea-8c97-9667ecb193b5.png)
> > 只不过每个定时脚本都需要jdCookie，有些麻烦
> > 大佬你写的这些脚本上传到阿里云是不是还需要修改啊，我看着和我的下载下来的不太一样

@mxzsw123456 你现在是只能阿里云可以,  腾讯云不能跑这个py代码吗?

**Comment by mxzsw123456** [comment]
> > > 可以，刚才用阿里云试了一下
> > > ![Snipaste_2020-08-11_22-51-32](https://user-images.githubusercontent.com/23739314/89912592-4ce1f980-dc25-11ea-8c97-9667ecb193b5.png)
> > > 只不过每个定时脚本都需要jdCookie，有些麻烦
> > > 大佬你写的这些脚本上传到阿里云是不是还需要修改啊，我看着和我的下载下来的不太一样
> 
> @mxzsw123456 你现在是只能阿里云可以, 腾讯云不能跑这个py代码吗?

我腾讯云和阿里云试了都不行,不知道哪里出问题了

**Comment by mxzsw123456** [comment]
> 你用云函数运行的，还是直接服务器里跑的

大佬我是直接放在云函数跑的报错，本地跑的正常没有问题

**Comment by Zero-S1** [comment]
> > 你用云函数运行的，还是直接服务器里跑的
> 
> 大佬我是直接放在云函数跑的报错，本地跑的正常没有问题

看是不是函数入口的问题
![HFJJ{NOEBQNV9S6OD_FWMV5](https://user-images.githubusercontent.com/23739314/90198491-69885800-de04-11ea-94ed-432ffc71902e.png)

**Comment by Zero-S1** [comment]
![Snipaste_2020-08-14_08-03-27](https://user-images.githubusercontent.com/23739314/90198590-af452080-de04-11ea-825c-b7780f5f81b6.png)
偷懒的话可以直接这样操作
将整个`for cookies in jdCookie.get_cookies():`放进 `def handler(event, context):`   handle()不需要在代码里调用，定时运行时会自动调用index.handler

**Comment by mxzsw123456** [comment]
> > > 你用云函数运行的，还是直接服务器里跑的
> > 
> > 
> > 大佬我是直接放在云函数跑的报错，本地跑的正常没有问题
> 
> 看是不是函数入口的问题
> ![HFJJ{NOEBQNV9S6OD_FWMV5](https://user-images.githubusercontent.com/23739314/90198491-69885800-de04-11ea-94ed-432ffc71902e.png)

![error](https://user-images.githubusercontent.com/47170569/90203464-6779c580-de13-11ea-8dfa-a53736931a1f.png)
执行就显示的这个，入口的handler在脚本里出现

**Comment by Zero-S1** [comment]
> > > > 你用云函数运行的，还是直接服务器里跑的
> > > 
> > > 
> > > 大佬我是直接放在云函数跑的报错，本地跑的正常没有问题
> > 
> > 
> > 看是不是函数入口的问题
> > ![HFJJ{NOEBQNV9S6OD_FWMV5](https://user-images.githubusercontent.com/23739314/90198491-69885800-de04-11ea-94ed-432ffc71902e.png)
> 
> ![error](https://user-images.githubusercontent.com/47170569/90203464-6779c580-de13-11ea-8dfa-a53736931a1f.png)
> 执行就显示的这个，入口的handler在脚本里出现

这报错不就是上面说的意思吗，你在仔细看看
