### ISSUE TITLE
京喜工厂能否考虑重新维护

### ISSUE THREAD

**Issue by DoveBoy** [Zero-S1/JD_tools#17]
非常想能够使用京喜工厂，大佬能否考虑一下重新启用jd_dreamfactory.py的维护？

**Comment by Zero-S1** [comment]
> 非常想能够使用京喜工厂，大佬能否考虑一下重新启用jd_dreamfactory.py的维护？

请参考 #11 ，目前基本功能仍在，暂时不考虑维护

**Comment by DoveBoy** [comment]
> > 非常想能够使用京喜工厂，大佬能否考虑一下重新启用jd_dreamfactory.py的维护？
> 
> 请参考 #11 ，目前基本功能仍在，暂时不考虑维护
> 
> 

是否考虑一下把目前项目利用Github Action，实现自动运行？

**Comment by Zero-S1** [comment]
刚才了解了一下Github Action，这个需要自己配置在自己的repo里吧

**Comment by DoveBoy** [comment]
> 刚才了解了一下Github Action，这个需要自己配置在自己的repo里吧

主要不太会，不知道怎么去写，能做个和这个差不多的就行https://github.com/ruicky/jd_sign_bot

**Comment by DoveBoy** [comment]
> 刚才了解了一下Github Action，这个需要自己配置在自己的repo里吧

已经fork这个项目，按照要求设置了github action，但是一直没自动运行，手动触发运行了一下，发现workflow中只有天天加速触发了，其他的脚本都没有运行

**Comment by Zero-S1** [comment]
> > 刚才了解了一下Github Action，这个需要自己配置在自己的repo里吧
> 
> 已经fork这个项目，按照要求设置了github action，但是一直没自动运行，手动触发运行了一下，发现workflow中只有天天加速触发了，其他的脚本都没有运行

请确认问题再提issue
![Snipaste_2020-08-15_09-03-32](https://user-images.githubusercontent.com/23739314/90302059-3b734880-ded6-11ea-8694-1e2edeb6ffb7.png)
