### ISSUE TITLE
如何添加京东第三方的店铺签到

### ISSUE THREAD

**Issue by tarianwei** [Zero-S1/JD_tools#18]
比如飞利浦官方旗舰店的签到是下面的链接，抓包出来是这样的：https://lzkj-isv.isvjcloud.com/sign/signActivity2?activityId=c716918ff3e74b3e86154abc836aa364

谢谢

**Comment by Zero-S1** [comment]
> 比如飞利浦官方旗舰店的签到是下面的链接，抓包出来是这样的：https://lzkj-isv.isvjcloud.com/sign/signActivity2?activityId=c716918ff3e74b3e86154abc836aa364
> 
> 谢谢

如果有类似st=XXX&sv=XXX&sign=XXXX的参数，那目前还做不了

**Comment by tarianwei** [comment]
> > 比如飞利浦官方旗舰店的签到是下面的链接，抓包出来是这样的：https://lzkj-isv.isvjcloud.com/sign/signActivity2?activityId=c716918ff3e74b3e86154abc836aa364
> > 谢谢
> 
> 如果有类似st=XXX&sv=XXX&sign=XXXX的参数，那目前还做不了

谢谢您 ，我在他这儿（https://github.com/Bonjour430/JingBeansCollector/blob/master/src/user_sign.py）看到有这样的代码，但本地测试没有返回值，是因为你说的这个原因吗？

**Comment by Zero-S1** [comment]
不晓得，也不打算做
