### ISSUE TITLE
希望添加京东APP上面的全民红包(又名锦鲤红包)

### ISSUE THREAD

**Issue by changer2222** [Zero-S1/JD_tools#2]
https://happy.m.jd.com/babelDiy/zjyw/3ugedFa7yA6NhxLN5gw2L3PF9sQC/index.html
https://h5.m.jd.com/babelDiy/Zeus/3ugedFa7yA6NhxLN5gw2L3PF9sQC/index.html
谢谢！

**Comment by Zero-S1** [comment]
需要哪些签到，麻烦你具体列一下

**Comment by changer2222** [comment]
你作的不少了，挺好的。
现在看能直接与优惠有的就是
1.JD APP上面-锦鲤红包
2.JD金融上面的-早起打卡 <--可以试试,完成自动打卡就行，支付那个麻烦点，可以人工处理。
3.JD到家的签到
4.京喜APP上面的免费水果
先把JD家族的给端了吧.

**Comment by Zero-S1** [comment]
1、其他app不考虑了，没兴趣薅
2、我的意思是具体列一下锦鲤红包的，我没研究明白

**Comment by changer2222** [comment]
不好意思，外出了，刚回来
这个其实收益比较低，每次任务完成才0.02钱，但是比较直接。
你访问那个页面就能看到。
一般访问后，出来任务列表

得任务列表
-------------------------
"https://api.m.jd.com/api?appid=jd_mp_h5&functionId=taskHomePage"
具体的任务 
functionId=getTaskDetailForColor

functionId=startTask

选一个任务 -宝洁大牌神券日 -1101355888
https://api.m.jd.com/api?appid=jd_mp_h5&functionId=taskReportForColor

**Comment by changer2222** [comment]
我根据你的其他脚本改装了一个，目前除了有一个任务不能完成外，其他的都可以正常取了
又能加点红包了
https://github.com/changer2222/JD_tools/commit/5497322ecdfb903ded63c3b411dbd1d27b51f4a0
等你有时间后，看看那个能不能实现

**Comment by Zero-S1** [comment]
https://api.m.jd.com/client.action?functionId=getCouponConfig 的这个暂时无法实现。
目前我晓得的京东的post请求中的data有两种形式，一种有通过st sv sign来检验data["body"]有没篡改；
另一种只要知道appid就行，无需验证，这个getCouponConfig 接口的appid不是“jd_mp_h5”；
至少我用iPhone抓到的是这个情况，你可以用其他设备试一试，也可以找一找或者猜一猜appid，哈

**Comment by changer2222** [comment]
看了以前抓的包
是通过st sv sign的检测的，没有appid
functionId=getCouponConfig&clientVersion=8.5.12&build=73078&client=android&d_brand=XXX&d_model=XXXX&osVersion=8.0.0&screen=1920*1080&partner=XXX&aid=XXXX&eid=eidXXXX&sdkVersion=26&lang=zh_CN&uuid=XXX&networkType=wifi&wifiBssid=XXXX&uts=AAA&st=timestamp&sign=XXX&sv=XXX



user-agent: okhttp/3.12.1 竟然是这个 

body=%7B%22childActivityUrl%22%3A%22openapp.jdmobile%3A%2F%2Fvirtual%3Fparams
有这个childActivityUrl带着开头的

body={"childActivityUrl":"openapp.jdmobile://virtual?params={\"category\":\"jump\",\"des\":\"couponCenter\"}","eid":"eidxxx","lat":"0.0","lng":"0.0","monitorRefer":"","monitorSource":"ccresource_android_index_config","pageClickKey":"Coupons_GetCenter","shshshfpb":"xxxxxx=="}&


注:eid是devicefinger （cookie里面也有)

**Comment by Zero-S1** [comment]
目前无解吧

**Comment by changer2222** [comment]
没好方法，先close了吧
