### ISSUE TITLE
宠汪汪报错了

### ISSUE THREAD

**Issue by changer2222** [Zero-S1/JD_tools#21]
{'currentTime': '2020-08-14 16-26-59', 'errorCode': 'P0001', 'errorMessage': '必填参数sku为空', 'success': False}
{'errorCode': 'follow_success', 'errorMessage': None, 'currentTime': 1597393619333, 'data': None, 'success': True}

**Comment by Zero-S1** [comment]
> {'currentTime': '2020-08-14 16-26-59', 'errorCode': 'P0001', 'errorMessage': '必填参数sku为空', 'success': False}
> {'errorCode': 'follow_success', 'errorMessage': None, 'currentTime': 1597393619333, 'data': None, 'success': True}

无视就好，这两个实际上是同一个任务的不同的两个接口，我搞不清是我弄乱了还是这两个会变化，有时候1有用，有时候2有用；懒得改了，索性全写了
