### ISSUE TITLE
JD上线了热8超级盲盒

### ISSUE THREAD

**Issue by changer2222** [Zero-S1/JD_tools#22]
https://blindbox.jd.com/

看看有没有时间搞搞

**Comment by Zero-S1** [comment]
> https://blindbox.jd.com/
> 
> 看看有没有时间搞搞

https://raw.githubusercontent.com/lxk0301/scripts/ccaa45aa9d94017d290fdc32e32ebe16cb77ee87/jd_mohe.js 请参照这个吧，不想自己写了

**Comment by changer2222** [comment]
我现在也不敢开太多了，定时任务已停了，变成了risk user了
运行speed.py的时候，看了返回信息。

**Comment by Zero-S1** [comment]
> 我现在也不敢开太多了，定时任务已停了，变成了risk user了
> 运行speed.py的时候，看了返回信息。

哪个返回信息？ speed应该是我最早开始写的，看里面的时间戳是3月份的，一直跑的定时任务，也没多大问题呀

**Comment by tarianwei** [comment]
> https://blindbox.jd.com/
> 
> 看看有没有时间搞搞

我用的是这个https://github.com/jinboyigu/lazy_script，把workflows里面不需要的禁用即可，如果要手动的话把：src/jd/blindBox/index.js里面async function lottery()这一段注释掉即可。

**Comment by changer2222** [comment]
> > 我现在也不敢开太多了，定时任务已停了，变成了risk user了
> > 运行speed.py的时候，看了返回信息。
> 
> 哪个返回信息？ speed应该是我最早开始写的，看里面的时间戳是3月份的，一直跑的定时任务，也没多大问题呀

def flyTask_state(cookies):
    params = (
        ('appid', 'memberTaskCenter'),
        ('functionId', 'flyTask_state'),
        ('body', '{"source":"game"}'),
        ('jsonp', '__jsonp1585235064779'),
        ('_', '1585235066058'),
    )
    response = requests.get('https://api.m.jd.com/',
                            headers=headers, params=params, cookies=cookies)
    result = _jsonp2dict(response.text)
    print (result)  <--因为运行不出来了，我加了print，看到提示risk user

**Comment by changer2222** [comment]
> > https://blindbox.jd.com/
> > 看看有没有时间搞搞
> 
> https://raw.githubusercontent.com/lxk0301/scripts/ccaa45aa9d94017d290fdc32e32ebe16cb77ee87/jd_mohe.js 请参照这个吧，不想自己写了

还是喜欢在python里面跑
自己给改了个
https://raw.githubusercontent.com/changer2222/JD_tools/master/JD_mohe.py
借鉴了一下lxk0301的调用

**Comment by changer2222** [comment]
好了，我这边正常了，我先close了

**Comment by 597712398** [comment]
> > > 我现在也不敢开太多了，定时任务已停了，变成了risk user了
> > > 运行speed.py的时候，看了返回信息。
> > 
> > 
> > 哪个返回信息？ speed应该是我最早开始写的，看里面的时间戳是3月份的，一直跑的定时任务，也没多大问题呀
> 
> def flyTask_state(cookies):
> params = (
> ('appid', 'memberTaskCenter'),
> ('functionId', 'flyTask_state'),
> ('body', '{"source":"game"}'),
> ('jsonp', '__jsonp1585235064779'),
> ('_', '1585235066058'),
> )
> response = requests.get('https://api.m.jd.com/',
> headers=headers, params=params, cookies=cookies)
> result = _jsonp2dict(response.text)
> print (result) <--因为运行不出来了，我加了print，看到提示risk user

risk_user都有返回，要看具体值吧，我的是"risk_user":0
