### ISSUE TITLE
moretree报错

### ISSUE THREAD

**Issue by changer2222** [Zero-S1/JD_tools#23]
sell
{"resultCode":-1,"resultMsg":"对不起该类型接口未开放调用权限，请联系管理员！","channelEncrypt":0}

**Comment by Zero-S1** [comment]
> sell
> {"resultCode":-1,"resultMsg":"对不起该类型接口未开放调用权限，请联系管理员！","channelEncrypt":0}

明显是接口进行维护了，你进app内操作一下就知道了。
