### ISSUE TITLE
跟着大佬学新东西， github action，跑test.py没问题， 跑脚本就报错，

### ISSUE THREAD

**Issue by lxk0301** [Zero-S1/JD_tools#24]
看着报错好像是指脚本读取ck从JD_tools/JD_tools/jdCookie.py里面拿了， 
![image](https://user-images.githubusercontent.com/21308593/90309666-0c33fa00-df1d-11ea-8e58-0fa6b1b38fef.png)

**Comment by Zero-S1** [comment]
对，没写太多判断   cookie要写成  pt_pin=xxxxx&pt_key=yyyyyy的形式

**Comment by lxk0301** [comment]
> 对，没写太多判断 cookie要写成 pt_pin=xxxxx&pt_key=yyyyyy的形式，保存在Settings - Secrets
> 还有，不要直接写进jdCookie，暴露账号了

我写反了， 正常的ck是 pt_key在前面， pt_pin在后面， 我刚才也么看， 直接复制了， 然后顺序反了。 我先玩玩你这个py的项目， 然后试试能不能跑我自己那个node.js的

**Comment by lxk0301** [comment]
@Zero-S1  请教问题， 我看这里京东ck是存储在 secrets里面， 然后获取GitHub 存储的secrets内容， 可以导入os, 然后直接拿， 这边大佬有知道nodejs那边如何获取吗？我网上搜索没看到

**Comment by Zero-S1** [comment]
process.env.JD_COOKIE

**Comment by lxk0301** [comment]
> process.env.JD_COOKIE

好像不行  ，是undefined
![image](https://user-images.githubusercontent.com/21308593/90311007-5ae79100-df29-11ea-949f-309b7ec2c4c9.png)

![image](https://user-images.githubusercontent.com/21308593/90311010-65a22600-df29-11ea-92e8-94adaae827de.png)

**Comment by Zero-S1** [comment]
我看了一下你写的yml ，env里先要定义 JD_COOKIE和access_token ，才能通过process.env拿到

**Comment by lxk0301** [comment]
> 我看了一下你写的yml ，env里先要定义 JD_COOKIE和access_token ，才能通过process.env拿到

懂了。原来这里面也有写。多谢解疑

**Comment by lxk0301** [comment]
@Zero-S1 目前打印。都是三个星号✳️
这是加密了吗？

```
npm notice created a lockfile as package-lock.json. You should commit this file.
10
added 67 packages from 138 contributors and audited 67 packages in 2.637s
11

12
9 packages are looking for funding
13
  run `npm fund` for details
14

15
found 0 vulnerabilities
16

17
github action test { CookieJD: '', CookieJD2: '' }
18
ACCESS_TOKEN ***
19
JD_COOKIE ***
20
github action test 
```

**Comment by Zero-S1** [comment]
> @Zero-S1 目前打印。都是三个星号✳️
> 这是加密了吗？
> 
> ```
> npm notice created a lockfile as package-lock.json. You should commit this file.
> 10
> added 67 packages from 138 contributors and audited 67 packages in 2.637s
> 11
> 
> 12
> 9 packages are looking for funding
> 13
>   run `npm fund` for details
> 14
> 
> 15
> found 0 vulnerabilities
> 16
> 
> 17
> github action test { CookieJD: '', CookieJD2: '' }
> 18
> ACCESS_TOKEN ***
> 19
> JD_COOKIE ***
> 20
> github action test 
> ```

会显示加密是因为别人也可以从actions 进入build，安全考虑

**Comment by lxk0301** [comment]
> > @Zero-S1 目前打印。都是三个星号✳️
> > 这是加密了吗？
> > ```
> > npm notice created a lockfile as package-lock.json. You should commit this file.
> > 10
> > added 67 packages from 138 contributors and audited 67 packages in 2.637s
> > 11
> > 
> > 12
> > 9 packages are looking for funding
> > 13
> >   run `npm fund` for details
> > 14
> > 
> > 15
> > found 0 vulnerabilities
> > 16
> > 
> > 17
> > github action test { CookieJD: '', CookieJD2: '' }
> > 18
> > ACCESS_TOKEN ***
> > 19
> > JD_COOKIE ***
> > 20
> > github action test 
> > ```
> 
> 会显示加密是因为别人也可以从actions 进入build，安全考虑

嗯。我以为是没有拿到内容，后面我就测试把你那个jdcookie.py文件也加个打印，看到也是显示三个星号，我就猜到了我那边应该也是拿到了值。
