### ISSUE TITLE
github action，宠汪汪好像有问题，一直报错

### ISSUE THREAD

**Issue by lxk0301** [Zero-S1/JD_tools#25]
```

执行自GitHub action
8
Traceback (most recent call last):
9
  File "JD_chongWangWang.py", line 230, in <module>
10
    desk(cookies)
11
  File "JD_chongWangWang.py", line 208, in desk
12
    for i in deskGoods if not i["status"]][:(taskChance-followCount)]
13
TypeError: 'NoneType' object is not iterable
14
执行自GitHub action ***
15
************************************************************
16
************************************************************
17
2020-08-15 23:13:04
18

19
报错请至 https://github.com/Zero-S1/JD_tools

邀请用户  2/3
30
每日签到  1/1
31
关注店铺  8/8
32
每日三餐  1/3
33
浏览频道  10/10
34
关注商品  6/6
35
看激励视频  3/3
36

37
【喂养状态】
38
  
39
现有积分: 9605
40
现有狗粮: 64
41
喂养次数: 51
42
宠物等级: 11
43
        
44

45
【bubble】
46
暂无
47

48
 【限时货柜】
49
 None/None
50
##[error]Process completed with exit code 1.

```
![5A05CA94-3EEF-45E0-A497-71E4953EBCB3](https://user-images.githubusercontent.com/21308593/90323346-9ec2b080-df92-11ea-84b1-1bc64637a59e.jpeg)
![42106E85-C3F4-4469-B05B-B302A62D6081](https://user-images.githubusercontent.com/21308593/90323347-a1bda100-df92-11ea-89c6-e718fa9a6ce9.png)
![6FA932F6-9CD0-47F2-B04C-ED9E787459CB](https://user-images.githubusercontent.com/21308593/90323348-a41ffb00-df92-11ea-8585-d0ecfec16c7b.png)

**Comment by Zero-S1** [comment]
活动下线了

**Comment by lxk0301** [comment]
> 活动下线了

看了一下。 啤酒的活动确实没了。我那边圈x跑起来倒没报错，你可能要加个判断修复一下了。

**Comment by lxk0301** [comment]
@Zero-S1 我看你刚才更新加了判断，我同步更新了一下。然后跑了一遍还是会报错。同样的提示

**Comment by Zero-S1** [comment]
贴一下报错信息

**Comment by lxk0301** [comment]
> 贴一下报错信息
刚re-run jobs拿的
```
执行自GitHub action
8
Traceback (most recent call last):
9
执行自GitHub action ***
10
  File "JD_chongWangWang.py", line 230, in <module>
11
    desk(cookies)
12
  File "JD_chongWangWang.py", line 208, in desk
13
    for i in deskGoods if not i["status"]][:(taskChance-followCount)]
14
TypeError: 'NoneType' object is not iterable
15
************************************************************
16
************************************************************
17
2020-08-16 00:08:50
18

19
报错请至 https://github.com/Zero-S1/JD_tools
20

21

22
【feed】
23
  time_error
24

25

26

27
任务      进度
28
--------------------
29
邀请用户  2/3
30
每日签到  1/1
31
关注店铺  8/8
32
每日三餐  1/3
33
浏览频道  10/10
```

**Comment by Zero-S1** [comment]
![Snipaste_2020-08-16_08-14-48](https://user-images.githubusercontent.com/23739314/90323791-9bcabe80-df98-11ea-9a81-4f126e8d0063.png)
奇怪，新增这句表示 跳出了函数了，可能你没有更新，还有一种可能就是 `/pet/getDeskGoodDetails`返回值不一样

**Comment by lxk0301** [comment]
> ![Snipaste_2020-08-16_08-14-48](https://user-images.githubusercontent.com/23739314/90323791-9bcabe80-df98-11ea-9a81-4f126e8d0063.png)
> 奇怪，新增这句表示 跳出了函数了，可能你没有更新，还有一种可能就是 `/pet/getDeskGoodDetails`返回值不一样

更新了。 你可以到我库里面看看的，pet/getDeskGoodDetails我看了，返回有值，其中deskGoods返回为null

**Comment by Zero-S1** [comment]
if not `null` 就会跳进print("活动下线")

**Comment by Zero-S1** [comment]
> > ![Snipaste_2020-08-16_08-14-48](https://user-images.githubusercontent.com/23739314/90323791-9bcabe80-df98-11ea-9a81-4f126e8d0063.png)
> > 奇怪，新增这句表示 跳出了函数了，可能你没有更新，还有一种可能就是 `/pet/getDeskGoodDetails`返回值不一样
> 
> 更新了。 你可以到我库里面看看的，pet/getDeskGoodDetails我看了，返回有值，其中deskGoods返回为null

还有，你这个签到和邀请用户是咋做的？

**Comment by lxk0301** [comment]
> > > ![Snipaste_2020-08-16_08-14-48](https://user-images.githubusercontent.com/23739314/90323791-9bcabe80-df98-11ea-9a81-4f126e8d0063.png)
> > > 奇怪，新增这句表示 跳出了函数了，可能你没有更新，还有一种可能就是 `/pet/getDeskGoodDetails`返回值不一样
> > 
> > 
> > 更新了。 你可以到我库里面看看的，pet/getDeskGoodDetails我看了，返回有值，其中deskGoods返回为null
> 
> 还有，你这个签到和邀请用户是咋做的？

啊？邀请和签到我没做。 那边设计到了来客有礼的小程序的token，但是这个token有时效。做不了。

**Comment by Zero-S1** [comment]
> > > > ![Snipaste_2020-08-16_08-14-48](https://user-images.githubusercontent.com/23739314/90323791-9bcabe80-df98-11ea-9a81-4f126e8d0063.png)
> > > > 奇怪，新增这句表示 跳出了函数了，可能你没有更新，还有一种可能就是 `/pet/getDeskGoodDetails`返回值不一样
> > > 
> > > 
> > > 更新了。 你可以到我库里面看看的，pet/getDeskGoodDetails我看了，返回有值，其中deskGoods返回为null
> > 
> > 
> > 还有，你这个签到和邀请用户是咋做的？
> 
> 啊？邀请和签到我没做。 那边设计到了来客有礼的小程序的token，但是这个token有时效。做不了。

我看你邀请已经完成两个了

**Comment by lxk0301** [comment]
@Zero-S1 手动邀请的。哈哈😄

**Comment by lxk0301** [comment]
@Zero-S1 加了判断后。你自己的号，跑起来没报错吗？这是我的号返回的数据

`{"errorCode":null,"errorMessage":null,"currentTime":1597538036317,"data":{"followCount":null,"taskChance":null,"taskReward":null,"deskGoods":null},"success":true} `

**Comment by Zero-S1** [comment]
![Snipaste_2020-08-16_08-38-54](https://user-images.githubusercontent.com/23739314/90324008-fca7c600-df9b-11ea-82f7-e4e4f0c3460e.png)
还真没报错

**Comment by lxk0301** [comment]
> ![Snipaste_2020-08-16_08-38-54](https://user-images.githubusercontent.com/23739314/90324008-fca7c600-df9b-11ea-82f7-e4e4f0c3460e.png)
> 还真没报错

尴尬😳，你试试github action？

**Comment by Zero-S1** [comment]
没问题
![Snipaste_2020-08-16_08-49-11](https://user-images.githubusercontent.com/23739314/90324131-6d031700-df9d-11ea-9c79-ba4a1fe6fa7d.png)

**Comment by Zero-S1** [comment]
这里有个surge脚本 cww_help.js，你看是否需要。需要手动点，比较麻烦
``` 
// 来客有礼宠汪汪强制助力= type=http-request,pattern=(^https:\/\/draw\.jdfcloud\.com\/\/pet\/enterRoom\?reqSource=weapp&invitePin=\w+(&inviteSource=task_invite&shareSource=h5&inviteTimeStamp=\d+&openId=\w+)?|^https:\/\/draw\.jdfcloud\.com\/\/pet\/helpFriend\?friendPin=\w+),requires-body=1,max-size=0,script-path=cww_help.js
// 手动点击 宠汪汪助力程序，自动更新为最新的时间戳，防止失效
// 每天助力三次

let url = $request.url
pin = "jd_57650a30ef6eb"  //强制为对方助力，有几率自动成为好友 (pin形如jd_xxxxxxxxx的几率大，其他的不会，原因未知)
timestamp = new Date().getTime()
newUrl = url.replace(/friendPin=.*?$/i, "friendPin=" + pin).replace(/invitePin=.*?$/i, "invitePin=" + pin).replace(/inviteTimeStamp=.*?$/i, "inviteTimeStamp=" + timestamp + "&")
console.log(newUrl)
$done({ url: newUrl })
```

**Comment by lxk0301** [comment]
> 这里有个surge脚本 cww_help.js，你看是否需要。需要手动点，比较麻烦
> 
> ```
> // 来客有礼宠汪汪强制助力= type=http-request,pattern=(^https:\/\/draw\.jdfcloud\.com\/\/pet\/enterRoom\?reqSource=weapp&invitePin=\w+(&inviteSource=task_invite&shareSource=h5&inviteTimeStamp=\d+&openId=\w+)?|^https:\/\/draw\.jdfcloud\.com\/\/pet\/helpFriend\?friendPin=\w+),requires-body=1,max-size=0,script-path=cww_help.js
> // 手动点击 宠汪汪助力程序，自动更新为最新的时间戳，防止失效
> // 每天助力三次
> 
> let url = $request.url
> pin = "jd_57650a30ef6eb"  //强制为对方助力，有几率自动成为好友 (pin形如jd_xxxxxxxxx的几率大，其他的不会，原因未知)
> timestamp = new Date().getTime()
> newUrl = url.replace(/friendPin=.*?$/i, "friendPin=" + pin).replace(/invitePin=.*?$/i, "invitePin=" + pin).replace(/inviteTimeStamp=.*?$/i, "inviteTimeStamp=" + timestamp + "&")
> console.log(newUrl)
> $done({ url: newUrl })
> ```

多谢。我有空看看，
对了，京东 超市，我添加到action好像也跑不起来，也会run fail。
要不你留个邮箱。我把我ck发给你 ，你调试一下宠汪汪？

**Comment by Zero-S1** [comment]
> > 这里有个surge脚本 cww_help.js，你看是否需要。需要手动点，比较麻烦
> > ```
> > // 来客有礼宠汪汪强制助力= type=http-request,pattern=(^https:\/\/draw\.jdfcloud\.com\/\/pet\/enterRoom\?reqSource=weapp&invitePin=\w+(&inviteSource=task_invite&shareSource=h5&inviteTimeStamp=\d+&openId=\w+)?|^https:\/\/draw\.jdfcloud\.com\/\/pet\/helpFriend\?friendPin=\w+),requires-body=1,max-size=0,script-path=cww_help.js
> > // 手动点击 宠汪汪助力程序，自动更新为最新的时间戳，防止失效
> > // 每天助力三次
> > 
> > let url = $request.url
> > pin = "jd_57650a30ef6eb"  //强制为对方助力，有几率自动成为好友 (pin形如jd_xxxxxxxxx的几率大，其他的不会，原因未知)
> > timestamp = new Date().getTime()
> > newUrl = url.replace(/friendPin=.*?$/i, "friendPin=" + pin).replace(/invitePin=.*?$/i, "invitePin=" + pin).replace(/inviteTimeStamp=.*?$/i, "inviteTimeStamp=" + timestamp + "&")
> > console.log(newUrl)
> > $done({ url: newUrl })
> > ```
> 
> 多谢。我有空看看，
> 对了，京东 超市，我添加到action好像也跑不起来，也会run fail。
> 要不你留个邮箱。我把我ck发给你 ，你调试一下宠汪汪？

861569352@qq.com 你可以加我qq
