### ISSUE TITLE
建议东东农场以及东东萌宠增加一个逻辑判断

### ISSUE THREAD

**Issue by DoveBoy** [Zero-S1/JD_tools#26]
现在这两个脚本在workflows里面到时间会无脑跑，一直浇水以及喂狗粮，直到把剩余水滴和狗粮喂完。建议增加一个逻辑判断，以东东农场为例子，**所有的浇水(10次浇水)任务，获取水滴任务完成后，如果剩余水滴大于等于60g,则继续浇水(保留部分水滴是用于完成第二天的浇水10次的任务)**，东东萌宠同理，希望开发者考虑一下。

**Comment by Zero-S1** [comment]
> 现在这两个脚本在workflows里面到时间会无脑跑，一直浇水以及喂狗粮，直到把剩余水滴和狗粮喂完。建议增加一个逻辑判断，以东东农场为例子，**所有的浇水(10次浇水)任务，获取水滴任务完成后，如果剩余水滴大于等于60g,则继续浇水(保留部分水滴是用于完成第二天的浇水10次的任务)**，东东萌宠同理，希望开发者考虑一下。

我脚本里已经提供自定义最大浇水次数了，不过可以考虑再加一个；另外你可以找人组队助力，这样就不用担心水滴不够了，哈
