### ISSUE TITLE
JD_Unfollow.py的建议

### ISSUE THREAD

**Issue by DoveBoy** [Zero-S1/JD_tools#27]
@Zero-S1 开发者大大，请问能否在不删除源代码的情况下，达到只取消关注店铺，而不取消商品关注的功能？尝试过把红框中的代码注释掉，但是运行报错。能否考虑参考一下[jd_unsubscribe.js](https://github.com/lxk0301/scripts/blob/master/jd_unsubscribe.js)的逻辑，只需要修改数值就能达到目的，比较方便。

![Screenshot_20200818-082853__01.jpg](https://user-images.githubusercontent.com/19201447/90457449-22fd6b00-e12e-11ea-8f46-dc729c13c397.jpg)

**Comment by Zero-S1** [comment]
直接注释掉第2个框就行

**Comment by DoveBoy** [comment]
> 直接注释掉第2个框就行

谢谢开发者！另外还有一个问题，jd_dreamfactory.py京喜工厂脚本，目前想用这个脚本来积攒电力。注释掉哪段代码，可以实现只收取电力以及做每日任务，但不投入电力的目的？

**Comment by Zero-S1** [comment]
![image](https://user-images.githubusercontent.com/23739314/90461051-e3d41780-e137-11ea-95ae-771a7bf00440.png)

**Comment by DoveBoy** [comment]
> ![image](https://user-images.githubusercontent.com/23739314/90461051-e3d41780-e137-11ea-95ae-771a7bf00440.png)
> 

谢谢！
