### ISSUE TITLE
easyMail.py notification.py 发邮件有个相同的问题

### ISSUE THREAD

**Issue by GitCourser** [Zero-S1/JD_tools#29]
我用网易163邮箱测试发送到qq邮箱收,结果有问题
网易"已发送"里,标题"test"正常,内容没有,但多了个"ATT00001.bin"的附件,下载后看内容就是"我是一封测试邮件 from easyMail.py"
qq邮箱"收件箱"这边,就只有标题"test",内容附件都是空的

**Comment by Zero-S1** [comment]
> 我用网易163邮箱测试发送到qq邮箱收,结果有问题
> 网易"已发送"里,标题"test"正常,内容没有,但多了个"ATT00001.bin"的附件,下载后看内容就是"我是一封测试邮件 from easyMail.py"
> qq邮箱"收件箱"这边,就只有标题"test",内容附件都是空的

我再研究研究，我用的qq邮箱发iCloud邮件没有问题，可能各家支持的格式不一样吧，具体我再看看

**Comment by Zero-S1** [comment]
> 我用网易163邮箱测试发送到qq邮箱收,结果有问题
> 网易"已发送"里,标题"test"正常,内容没有,但多了个"ATT00001.bin"的附件,下载后看内容就是"我是一封测试邮件 from easyMail.py"
> qq邮箱"收件箱"这边,就只有标题"test",内容附件都是空的

误用了MIMEMultipart，这个是发附件的模块。但是发现SMTP服务耗时过长，我这边都是20s以上

**Comment by GitCourser** [comment]
昨天没改前还能发,只是有标题没内容,今天修改后的代码直接不能发送,信息如下

`通知服务测试
SMTP服务启动
邮件登录成功
Error: 无法发送邮件 (554, b'DT:SPM 163 smtp8,DMCowAD3_w9cOD5fgfMwJg--.16436S2 1597913181,please see http://mail.163.com/help/help_spam_16.htm?hostid=smtp8&time=1597913181')
耗时:  0.3441355228424072 s`

**Comment by Zero-S1** [comment]
我用QQ一点问题没有，你试试把邮件里的“测试”，之类的去掉，看是不是触发什么拦截规则了

**Comment by GitCourser** [comment]
试了,随便改成什么标题和内容都发不了,但用昨天的代码,标题里有"测试"也能发

**Comment by Zero-S1** [comment]
> 昨天没改前还能发,只是有标题没内容,今天修改后的代码直接不能发送,信息如下
> 
> 通知服务测试
> SMTP服务启动
> 邮件登录成功
> Error: 无法发送邮件 (554, b'DT:SPM 163 smtp8,DMCowAD3_w9cOD5fgfMwJg--.16436S2 1597913181,please see http://mail.163.com/help/help_spam_16.htm?hostid=smtp8&time=1597913181')
> 耗时: 0.3441355228424072 s

看错误码是这个原因，`554 DT:SPM 发送的邮件内容包含了未被许可的信息，或被系统识别为垃圾邮件。请检查是否有用户发送病毒或者垃圾邮件；`

百度上检索网易smtp的554错误有很多条目
[https://blog.csdn.net/jerry11112/article/details/81213162](https://blog.csdn.net/jerry11112/article/details/81213162)
你换换QQ邮箱试了吗？

**Comment by Zero-S1** [comment]
![Snipaste_2020-08-20_17-26-16](https://user-images.githubusercontent.com/23739314/90752714-4ed54800-e30a-11ea-86f3-a15f9693925a.png)
或者你把这里的改改，我还是怀疑触发关键词了

**Comment by Zero-S1** [comment]
> ![Snipaste_2020-08-20_17-26-16](https://user-images.githubusercontent.com/23739314/90752714-4ed54800-e30a-11ea-86f3-a15f9693925a.png)
> 或者你把这里的改改，我还是怀疑触发关键词了

[https://blog.csdn.net/weixin_41789943/article/details/82348946](https://blog.csdn.net/weixin_41789943/article/details/82348946)目前看来可能是这篇文章提到的问题，可能是163不支持这种Header提供昵称的形式，由于我没有163邮箱，你可以按照这篇文章的方法改一下

**Comment by GitCourser** [comment]
> > ![Snipaste_2020-08-20_17-26-16](https://user-images.githubusercontent.com/23739314/90752714-4ed54800-e30a-11ea-86f3-a15f9693925a.png)
> > 或者你把这里的改改，我还是怀疑触发关键词了
> 
> https://blog.csdn.net/weixin_41789943/article/details/82348946目前看来可能是这篇文章提到的问题，可能是163不支持这种Header提供昵称的形式，由于我没有163邮箱，你可以按照这篇文章的方法改一下

多谢,就是这个问题,我改成这样可以发了,receivers由列表改成字符串
`    message['From'] = mail_user
    message['To'] = receivers
`
