### ISSUE TITLE
moneyTree这个,我调用user_info接口,服务器返回服务器繁忙,是什么原因呢?

### ISSUE THREAD

**Issue by lxk0301** [Zero-S1/JD_tools#3]
用的是post请求, 然后body里面直接是
```
data = {
    'reqData': '{"shareType":1,"source":0,"riskDeviceParam":"{\\\\"fp\\\\":\\\\"\\\\",\\\\"eid\\\\":\\\\"\\\\",\\\\"sdkToken\\\\":\\\\"\\\\",\\\\"sid\\\\":\\\\"\\\\"}"}'
  }

```
未格式化成字符串

![image](https://user-images.githubusercontent.com/21308593/85857070-b6c85000-b7eb-11ea-822f-bf6a6db53c1b.png)
![image](https://user-images.githubusercontent.com/21308593/85857172-ea0adf00-b7eb-11ea-990e-ec907fb8098a.png)

![image](https://user-images.githubusercontent.com/21308593/85857086-bf208b00-b7eb-11ea-91a5-8bcfd19356dd.png)

**Comment by Zero-S1** [comment]
不清楚，你可以贴一下你写的js

**Comment by lxk0301** [comment]
我用的是js, 然后好像是body里面的reqData, 需要urlenCode, 但是我转码后, 还是请求有问题我看到 ,然后在login接口的时候,我就写死了body,现在是收取金果的时候, 又出现问题了.
https://gitee.com/lxk0301/scripts/blob/master/jd_moneyTree2.js

**Comment by Zero-S1** [comment]
我看不出什么问题，是不是风控

**Comment by changer2222** [comment]
> 我用的是js, 然后好像是body里面的reqData, 需要urlenCode, 但是我转码后, 还是请求有问题我看到 ,然后在login接口的时候,我就写死了body,现在是收取金果的时候, 又出现问题了.
> https://gitee.com/lxk0301/scripts/blob/master/jd_moneyTree2.js

昨天正巧search到你的gitee，怎么不在github上面放个，多方便。
另外boxjs是个什么东东？朋友用的qx是直接装？

**Comment by lxk0301** [comment]
> > 我用的是js, 然后好像是body里面的reqData, 需要urlenCode, 但是我转码后, 还是请求有问题我看到 ,然后在login接口的时候,我就写死了body,现在是收取金果的时候, 又出现问题了.
> > https://gitee.com/lxk0301/scripts/blob/master/jd_moneyTree2.js
> 
> 昨天正巧search到你的gitee，怎么不在github上面放个，多方便。
> 另外boxjs是个什么东东？朋友用的qx是直接装？

@changer2222 qx是IOS上的一个代理软件,可以翻墙,使用脚本,还要cron定时器功能.box 也是基于qx的玩法

**Comment by lxk0301** [comment]
> 我看不出什么问题，是不是风控

@Zero-S1 是js请求参数body传值的问题. 像login接口. body里面不知道是不是要编码一下传递过去.

**Comment by lxk0301** [comment]
@Zero-S1  js那边的问题我解决了.
```
  const params = {
    "sharePin":"",
    "shareType":1,
    "channelLV":"",
    "source":0,
    "riskDeviceParam":{"eid":"","dt":"","ma":"","im":"","os":"","osv":"","ip":"","apid":"","ia":"","uu":"","cv":"","nt":"","at":"1","fp":"","token":""}
  }
// 第一先对riskDeviceParam进行格式化
  params.riskDeviceParam = JSON.stringify(params.riskDeviceParam);
//riskDeviceParam格式化后,第二再对整个params进行格式化, 然后在进行encodeURIComponent编码
//encodeURIComponent(JSON.stringify(params));
const body = 'reqData=' + encodeURIComponent(JSON.stringify(params));
```
