### ISSUE TITLE
上传到腾讯云函数出现的问题

### ISSUE THREAD

**Issue by niumingyuan** [Zero-S1/JD_tools#38]
不知道是不是执行方法的问题，请看一下图片：https://imgchr.com/i/wkJrLD

**Comment by niumingyuan** [comment]
。。

**Comment by Zero-S1** [comment]
> 不知道是不是执行方法的问题，请看一下图片：https://imgchr.com/i/wkJrLD

没用过你这个云函数，但很明显你可能理解错了【执行方法】的意思

**Comment by niumingyuan** [comment]
行吧，我还是继续用github action ,感谢回复，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lance"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午4:44
收件人: "Zero-S1/JD_tools"<JD_tools@noreply.github.com&gt;; 
抄送: "3170418865"<3170418865@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Zero-S1/JD_tools] 上传到腾讯云函数出现的问题 (#38)





  
不知道是不是执行方法的问题，请看一下图片：https://imgchr.com/i/wkJrLD
  
没用过你这个云函数，但很明显你可能理解错了【执行方法】的意思
