### ISSUE TITLE
github action手动触发验证代码可执行性建议

### ISSUE THREAD

**Issue by DoveBoy** [Zero-S1/JD_tools#39]
有时更新项目pull request后，会出现merge失败，需要解决冲突。此时没有好办法解决，只能删除项目，重新fork。一切设置完成后，每次需要验证设置是否正确以及github action能否正常工作时总是特别麻烦，作者可否在workflows文件夹下的每个yml中加入“watch:types: started”一段代码，使其能够通过点击star来手动触发github action？

**Comment by Zero-S1** [comment]
部分yml已经添加，有些脚本一直没有变化的没有添加

**Comment by DoveBoy** [comment]
> 部分yml已经添加，有些脚本一直没有变化的没有添加

已测试，可以用了，感谢开发者这么快的响应速度😀
