### ISSUE TITLE
moneyTree这个左上角的任务程序没有作

### ISSUE THREAD

**Issue by changer2222** [Zero-S1/JD_tools#4]
moneyTree这个左上角的任务程序没有作，看了一下，有些任务可以得金果的。
逛活动的有些。7+7次。

**Comment by chenchenchenze** [comment]
大佬，你用什么运行的？

**Comment by changer2222** [comment]
> 大佬，你用什么运行的？

py3呀

**Comment by Zero-S1** [comment]
> moneyTree这个左上角的任务程序没有作，看了一下，有些任务可以得金果的。
> 逛活动的有些。7+7次。

逛活动那个抓包了没整明白，感觉收益不大，弃坑了，哈哈
