### ISSUE TITLE
jd_supermarket运行bug

### ISSUE THREAD

**Issue by DoveBoy** [Zero-S1/JD_tools#40]
最近pull request最新代码后，京小超运行一直报错，不知道是不是京东那边改了什么东西，麻烦开发者看下
![Screenshot_20200914-075818](https://user-images.githubusercontent.com/19201447/93031841-70eb8d00-f660-11ea-9d26-101261ccff91.jpg)

**Comment by Zero-S1** [comment]
已经修改了

**Comment by DoveBoy** [comment]
> 已经修改了

现在活动又重新上线了，貌似1000京豆打包那个也不用抢了。目前代码能改成带判断那种吗？有活动就运行兑换京豆，没活动就不兑换而不会一直报错
