### ISSUE TITLE
京东领券中心，jd_red_packet运行失败

### ISSUE THREAD

**Issue by DoveBoy** [Zero-S1/JD_tools#43]
@Zero-S1 在群里反馈过这个问题，使用的是大佬修改后的脚本（添加了打印语句），目前运行脚本会在第一次30s的任务中卡住，求解决办法
![Screenshot_20200928-090601](https://user-images.githubusercontent.com/19201447/94381008-59d19280-016a-11eb-98da-423237aabf4c.jpg)

**Comment by Zero-S1** [comment]
https://github.com/Zero-S1/JD_tools/blob/ac761e1f7c80b71c8e139aeaba7f0ba54bdbc033/JD_red_packet.py#L146

更新了，为什么你的账号返回值和别人都不太一样 。黑号了吗

**Comment by DoveBoy** [comment]
> https://github.com/Zero-S1/JD_tools/blob/ac761e1f7c80b71c8e139aeaba7f0ba54bdbc033/JD_red_packet.py#L146
> 
> 更新了，为什么你的账号返回值和别人都不太一样 。黑号了吗

没有黑号吧，我一直可以正常领活动，没有出现活动被限制的情况

**Comment by DoveBoy** [comment]
我的京东账号信誉等级4级，Plus分102，按道理说不是黑号，而且活动都能正常参加

**Comment by Zero-S1** [comment]
建议咨询原作者  `@changer2222`
