### ISSUE TITLE
jd_farm_help运行报错

### ISSUE THREAD

**Issue by DoveBoy** [Zero-S1/JD_tools#44]
昨天之前运行一直都是正常的，从9.28之后开始运行都是错误，大佬看下是什么情况
![image](https://user-images.githubusercontent.com/19201447/94391452-08d09700-0188-11eb-94c0-588f7a0ec261.png)
![image](https://user-images.githubusercontent.com/19201447/94391464-0d954b00-0188-11eb-9951-accfef6ba6aa.png)
![image](https://user-images.githubusercontent.com/19201447/94391496-27369280-0188-11eb-8ea3-c943958ed59d.png)

**Comment by Zero-S1** [comment]
https://github.com/Zero-S1/JD_tools/blob/22d84fef02cbf32941052e3f33cf4edff681d5d9/jd_farm_help.py#L71

更新看看 返回值是什么

**Comment by DoveBoy** [comment]
> https://github.com/Zero-S1/JD_tools/blob/22d84fef02cbf32941052e3f33cf4edff681d5d9/jd_farm_help.py#L71
> 
> 更新看看 返回值是什么

报错
![image](https://user-images.githubusercontent.com/19201447/94394070-0291e900-018f-11eb-8ff6-5ab2e9e2d0b7.png)

**Comment by Zero-S1** [comment]
你直接停掉这个脚本吧 ，反正是为别人助力的
