### ISSUE TITLE
JD_chongWangWang运行出错

### ISSUE THREAD

**Issue by CzRQ** [Zero-S1/JD_tools#45]
![Snipaste_9-28   17-40-13](https://user-images.githubusercontent.com/44220736/94417203-5eba3480-01b2-11eb-85b1-a5b4346a418b.png)
![Snipaste_9-28   17-41-29](https://user-images.githubusercontent.com/44220736/94417208-6083f800-01b2-11eb-8ec6-1b8d88589df8.png)

Traceback (most recent call last):
************************************************************
  File "JD_chongWangWang.py", line 293, in <module>
    reward(cookies)
  File "JD_chongWangWang.py", line 225, in reward
************************************************************
2020-09-28 09:31:37
    giftSaleInfos = result["data"]["levelSaleInfos"]["giftSaleInfos"]
TypeError: 'NoneType' object is not subscriptable###

**Comment by Zero-S1** [comment]
https://github.com/Zero-S1/JD_tools/blob/a2dfd55cac202d8b1fd4790306e686566995b590/JD_chongWangWang.py#L225
更新完看报错是什么

**Comment by CzRQ** [comment]
在添加了print(result)后，本地运行报错如图
<img width="923" alt="Snipaste_2020-09-29_21-34-59" src="https://user-images.githubusercontent.com/44220736/94565493-de6ffe00-029b-11eb-9907-7cd62370b1bc.png">

**Comment by Zero-S1** [comment]
你这个 兑奖页面返回为空  进入app看看是什么情况
检查抓包信息 `gift/getHomeInfo`

**Comment by happyzjhao** [comment]
我的一开始也报错 京东app打开兑换页面 再次重新运行又没报错了
