### ISSUE TITLE
发现个农场隐藏任务

### ISSUE THREAD

**Issue by GitCourser** [Zero-S1/JD_tools#46]
点农场中间的小鸭子,随机获得水滴和道具卡
可以玩几次,具体没数,但没超过10次,最后小鸭子说休息就结束

**Comment by Zero-S1** [comment]
我这边没有这个

**Comment by DoveBoy** [comment]
> 我这边没有这个

我也有这个

**Comment by Zero-S1** [comment]
会抓包的给我发一份内容也行

**Comment by GitCourser** [comment]
直接用在电脑上用浏览器打开网页版农场就能看到
https://h5.m.jd.com/babelDiy/Zeus/2rooSNdvm3kS9y21MYCnek4SaoWj/index.html

**Comment by Zero-S1** [comment]
https://github.com/Zero-S1/JD_tools/blob/8dcbbfa7cc1972b3b6cc221246a0599daf710ab0/JD_dongdongFarm.py#L66

更新

**Comment by GitCourser** [comment]
大佬,请教个问题

小鸭子我自己用chrome的f12工具看抓包getFullCollectionReward这个用的是get方法,脚本里用的是post方法,
我自己试了,用get方法,不管运行几次得到结果都是相同的,code和haslimit都不变,就是下面的结果
`{'code': '0', 'hasLimit': False, 'statisticsTimes': None, 'imageUrl': 'https://m.360buyimg.com/babel/jfs/t1/118793/39/18430/116972/5f6b2569Ea07cf4c8/056cc8fafb50a100.png', 'sysTime': 1601380381387, 'message': None, 'type': 3, 'title': '小鸭子和好朋友玩耍去啦'}`

用post方法运行5次,结果都不同,而且5次后code会变成10,证明用post是对的,但为什么浏览器抓包是get方法?

**Comment by Zero-S1** [comment]
具体抓包的贴一下 我没有备份

**Comment by GitCourser** [comment]
只能明天了,我刚才忘记复制,结果鸭子次数用完,现在点不了,等明天次数刷新

另外还有个问题,duck函数中为什么要先运行一次,然后再用for循环4次,为什么不直接用for循环5次?

**Comment by Zero-S1** [comment]
> 只能明天了,我刚才忘记复制,结果鸭子次数用完,现在点不了,等明天次数刷新
> 
> 另外还有个问题,duck函数中为什么要先运行一次,然后再用for循环4次,为什么不直接用for循环5次?

没啥特别的用意，本来想进入duck函数时检查某个接口看看还有几次机会，然后执行几次`getFullCollectionReward`，后来没找到然后忘了改了

**Comment by GitCourser** [comment]
小鸭子抓包

Request URL: https://api.m.jd.com/client.action?functionId=getFullCollectionReward&body=%7B%22type%22%3A2%2C%22version%22%3A6%2C%22channel%22%3A1%7D&appid=wh5
Request Method: GET

get没有data,只有url参数
functionId: getFullCollectionReward
body: {"type":2,"version":6,"channel":1}
appid: wh5

**Comment by Zero-S1** [comment]
那我也不清楚了

**Comment by GitCourser** [comment]
找到原因了
`getTemplate`中定义了`version=4`,所以这个6没实际没传进去
我在`body["version"] = 4`前面加上`if not "version" in body:`就搞定了
