### ISSUE TITLE
京小超运行出错

### ISSUE THREAD

**Issue by DoveBoy** [Zero-S1/JD_tools#50]
京东现在对京小超做了活动调整，店铺任务现在没有了，导致现在京小超运行执行到店铺任务后会报错，请开发者加个判断语句，暂时不执行店铺任务（不知道后期会不会重新上线）[京小超报错](https://github.com/DoveBoy/JD_tools/runs/1244814951?check_suite_focus=true)

![image](https://user-images.githubusercontent.com/19201447/95800575-460d5b00-0d2a-11eb-8870-6bfc10e2e35a.png)
![image](https://user-images.githubusercontent.com/19201447/95800691-95538b80-0d2a-11eb-80e8-f17dad993ef2.png)

**Comment by happyzjhao** [comment]
店铺任务怎么有时没有 有时有 我昨天失败 今天又成功了
![image](https://user-images.githubusercontent.com/56525354/95840659-0456d180-0d77-11eb-9ec7-555e6bb6bbd5.png)

**Comment by happyzjhao** [comment]
![image](https://user-images.githubusercontent.com/56525354/95840740-1fc1dc80-0d77-11eb-92fc-0e0a10ddb25d.png)
