### ISSUE TITLE
农场自动处理助力结果

### ISSUE THREAD

**Issue by changer2222** [Zero-S1/JD_tools#6]
在help那里
 def masterHelp(cookies):
    print("\n【助力得水】")
    help_me_list = postTemplate(cookies, "masterHelpTaskInitForFarm", {})
    # print (help_me_list)
    print(
        f"""完成进度 {len(help_me_list["masterHelpPeoples"])}/5   {help_me_list["f"]}""")
    if help_me_list["masterGotFinal"] :
        print("奖励已经领取")
    if len(help_me_list["masterHelpPeoples"]) >= 5 and not help_me_list["masterGotFinal"] :
        print("领取助力奖励")
        print(postTemplate(cookies, "masterGotFinishedTaskForFarm", {}))
    if not help_me_list["f"]:
        help_me_list1 = postTemplate(
            cookies, "masterGotFinishedTaskForFarm", {})
        print(help_me_list1)

**Comment by Zero-S1** [comment]
"masterGotFinal"  和 "f"  好像是一致的

**Comment by changer2222** [comment]
> "masterGotFinal" 和 "f" 好像是一致的

嗯
