### ISSUE TITLE
京东超市pk异常

### ISSUE THREAD

**Issue by Su-yj** [Zero-S1/JD_tools#62]
![image](https://user-images.githubusercontent.com/37967623/101637526-d97fb580-3a67-11eb-9ed1-32554b9948b0.png)

**Comment by Su-yj** [comment]
![image](https://user-images.githubusercontent.com/37967623/101639288-0fbe3480-3a6a-11eb-9eb1-abed9e70ba87.png)

**Comment by Zero-S1** [comment]
已经提交修改了
