### ISSUE TITLE
Please write in English.

### ISSUE THREAD

**Issue by Almas-Ali** [Zero-S1/JD_tools#66]
Hi,
Please write all those tools in English to understand all settings.

**Comment by Zero-S1** [comment]
Sorry, you probably don't need this script if you can't read Chinese. This tool is for a Chinese app only. 
I am not going to translate it into English.

**Comment by SIXGODLI** [comment]
干得漂亮

**Comment by gurenn** [comment]
反手就是一个赞，如果老外需要用到JD的自动签到应该也中文水平不错。不存在需要英文环境
