### ISSUE TITLE
错误如图

### ISSUE THREAD

**Issue by 735450178** [Zero-S1/JD_tools#67]
你好，我在GitHub上部署了，运行尝试多次都报错，我JD_COOKI的填写格式为  pt_key=aaaaaabbbbbb;pt_pin=nsjahjqfjffuu;
如果是填写格式不对，请您给一个正确的格式谢谢，附上错误截图。
![GQ$)DXN OHWZ~SI(3OK)5`E](https://user-images.githubusercontent.com/64771597/103452562-d943a480-4d0b-11eb-9626-e866196a564e.png)

**Comment by humaokun1990** [comment]
你复制完整的cookie试一试，这个格式或许不是这个脚本使用的

**Comment by SlyLi** [comment]
> 你好，我在GitHub上部署了，运行尝试多次都报错，我JD_COOKI的填写格式为 pt_key=aaaaaabbbbbb;pt_pin=nsjahjqfjffuu;
> 如果是填写格式不对，请您给一个正确的格式谢谢，附上错误截图。
> ![GQ$)DXN OHWZ~SI(3OK)5`E](https://user-images.githubusercontent.com/64771597/103452562-d943a480-4d0b-11eb-9626-e866196a564e.png)

你把cookie格式换成 pt_key=aaaaaabbbbbb&pt_pin=nsjahjqfjffuu$ 试试

**Comment by Zero-S1** [comment]
单账号为`pt_key=aaaaaabbbbbb&pt_pin=ccccccccccccddddddddd`  ；


如果需要多账号
```
pt_key=aaaaaabbbbbb&pt_pin=ccccccccccccddddddddd
pt_key=mmmmmmmnnnn&pt_pin=xxxxxxxxxxxxxdddddd

**Comment by 735450178** [comment]
已解决，感谢
