### ISSUE TITLE
请问cookie正确的格式是什么

### ISSUE THREAD

**Issue by lulingliangzai** [Zero-S1/JD_tools#68]
我在运行宠汪汪的过程中出现了下面的提示：  
File "jd_joy.py", line 1, in <module>
    import jdCookie
  File "/home/runner/work/JD_tools/JD_tools/jdCookie.py", line 42, in <module>
    pt_pin = re.findall(r'pt_pin=(.*?)&', line)[0]
IndexError: list index out of range
Error: Process completed with exit code 1.
请问是cookie的填写格式错误了，还是其他的什么原因呢？

**Comment by Zero-S1** [comment]
https://github.com/Zero-S1/JD_tools/issues/67#issuecomment-754350531

**Comment by lulingliangzai** [comment]
> [#67 (comment)](https://github.com/Zero-S1/JD_tools/issues/67#issuecomment-754350531)

好的，谢谢了
