### ISSUE TITLE
本地执行正常，actions运行错误

### ISSUE THREAD

**Issue by lulingliangzai** [Zero-S1/JD_tools#69]
按照大佬的教程获取了pt_key和pt_pin，在本地执行能正常运行，没有问题，但是通过actions来运行，每次都是出现下面图片的提示错误，cookie按照大佬昨天提示的格式pt_key=aaaaabbbbbb&pt_pin=cccccccddddd存放在secret中，现在也没能排查出具体原因，请大佬指点
<img width="671" alt="屏幕截图 2021-01-05 135302" src="https://user-images.githubusercontent.com/76714957/103611591-911bc080-4f5d-11eb-90d2-d72b6812aea3.png">

**Comment by lulingliangzai** [comment]
大佬，您好，我看您的教程，发现自己少了一个main.yml，自己不知道如何配置，还请teamviewer远程指导一下，谢谢。我的邮箱地址：sxl2010904003@outlook.com，盼复！

**Comment by Zero-S1** [comment]
![image](https://user-images.githubusercontent.com/23739314/103631895-89204880-4f7e-11eb-8402-413b127217e3.png)
不好意思，之前写错了。已经更正。

教程里不涉及main.yml，可能你看错了

**Comment by lulingliangzai** [comment]
> ![image](https://user-images.githubusercontent.com/23739314/103631895-89204880-4f7e-11eb-8402-413b127217e3.png)
> 不好意思，之前写错了。已经更正。
> 
> 教程里不涉及main.yml，可能你看错了

好的，收到，

**Comment by lulingliangzai** [comment]
> ![image](https://user-images.githubusercontent.com/23739314/103631895-89204880-4f7e-11eb-8402-413b127217e3.png)
> 不好意思，之前写错了。已经更正。
> 
> 教程里不涉及main.yml，可能你看错了


请问这个是什么问题呢？
<img width="658" alt="屏幕截图 2021-01-05 201432" src="https://user-images.githubusercontent.com/76714957/103645726-77956b80-4f93-11eb-81af-d0a3f1bea30a.png">
