### ISSUE TITLE
东东萌宠今天又加了两个任务，没有在执行里面

### ISSUE THREAD

**Issue by changer2222** [Zero-S1/JD_tools#7]
在“做任务赚狗粮”中，多了两个“去逛逛”
不过查了一下，在APP里面没有，微信小程序里面有

**Comment by Zero-S1** [comment]
我这边没有看到，你可以发一下截图
据我观察，是用 browseSingleShopInit2 (冰淇淋会场) 替换了 原来的 browseSingleShopInit，估计是临时的

**Comment by changer2222** [comment]
不折腾他了，今天跑了你的新的code，这个已执行了。
